import { createLocalEmbedding } from "@/lib/local-embeddings";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

async function retrieveFlashcardContext(
  topic: string,
  userId: string,
  collectionId?: string | null,
  documentIds?: string[]
) {
  const queryEmbedding = await createLocalEmbedding(topic);

  const { data, error } = await supabase.rpc("match_document_chunks", {
    query_embedding: queryEmbedding,
    match_user_id: userId,
    match_collection_id: collectionId || null,
    match_document_ids:
      documentIds && documentIds.length > 0 ? documentIds : null,
    match_count: 10,
  });

  if (error) throw error;

  return data || [];
}

async function generateWithLocalLlm(prompt: string) {
  const ollamaRes = await fetch(
    `${process.env.LOCAL_LLM_URL || "http://localhost:11434"}/api/chat`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: process.env.LOCAL_LLM_MODEL || "llama3.1:8b",
        messages: [
          {
            role: "user",
            content: prompt,
          },
        ],
        stream: false,
      }),
    }
  );

  if (!ollamaRes.ok) {
    const errorText = await ollamaRes.text();
    throw new Error(`Ollama error: ${errorText}`);
  }

  const ollamaData = await ollamaRes.json();

  return (
    ollamaData.message?.content ||
    "No response generated by local model."
  );
}

export async function POST(req: Request) {
  try {
    const {
      topic,
      cardCount,
      difficulty,
      userId,
      collectionId,
      documentIds,
    } = await req.json();

    if (!topic) {
      return Response.json(
        { error: "Missing topic." },
        { status: 400 }
      );
    }

    if (!userId) {
      return Response.json(
        { error: "Missing userId." },
        { status: 400 }
      );
    }

    const count = Number(cardCount || 20);

    const chunks = await retrieveFlashcardContext(
      topic,
      userId,
      collectionId,
      documentIds
    );

    const context = chunks
      .map((chunk: any, index: number) => {
        return `Source ${index + 1} (${chunk.file_name}):\n${chunk.content}`;
      })
      .join("\n\n---\n\n");

    const prompt = `
You are a nuclear engineering training assistant.

Create ${count} study flashcards.

Topic:
${topic}

Difficulty:
${difficulty || "intermediate"}

Use the document context below when relevant.
If the context is insufficient, say that briefly before the flashcards.
Cite source filenames where helpful.

DOCUMENT CONTEXT:
${context || "No relevant document context found."}

Required format:

# Flashcards

1. Front: ...
   Back: ...

2. Front: ...
   Back: ...

3. Front: ...
   Back: ...

# Sources Used
- filename
`;

    const flashcards = await generateWithLocalLlm(prompt);

    return Response.json({
      flashcards,
      sources: chunks,
    });
  } catch (error) {
    console.error(error);

    return Response.json(
      { error: "Failed to generate flashcards." },
      { status: 500 }
    );
  }
}